navbar:
  blog_title: Ink  Dyeing
  ground_glass:
    enable: true
index:
  banner_img: /images/uploads/none.png
 # banner_img_height: 100
  slogan:
    text: " 保持热爱，奔赴山海 "
  # " 墨染水云间，流年如画轻盈了幽闲"
post:
  banner_img: /images/uploads/none.png
  #https://imgapi.xl0408.top/index.php
  banner_img_height: 70
  default_index_img: https://i.imgtg.com/2022/09/14/yAzLX.png
  #/images/uploads/none.png
archive:
  banner_img: /images/uploads/none.png
  banner_img_height: 80
  subtitle: null
category:
  banner_img: /images/uploads/none.png
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: /images/uploads/none.png
  banner_img_height: 80
  subtitle: null
about:
  banner_img: /images/uploads/none.png
  banner_img_height: 81
  subtitle: null
  avatar: /images/uploads/yutzi.jpg
  name: 墨染_nlx
  intro: My blog
