navbar:
  blog_title: Ink  Dyeing
  ground_glass:
    enable: true
index:
  banner_img: https://moran.0oo0.top/images/ink-index.jpg
  banner_img_height: 100
  slogan:
    text: " 墨染水云间，流年如画轻盈了幽闲。"
post:
  banner_img: https://moran.0oo0.top/images/ink-banner_img.jpg
  banner_img_height: 70
  default_index_img: https://i.imgtg.com/2022/09/14/yAzLX.png
archive:
  banner_img: https://moran.0oo0.top/images/ink-archive.jpg
  banner_img_height: 80
  subtitle: null
category:
  banner_img: https://moran.0oo0.top/images/ink-category.jpg
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: https://moran.0oo0.top/images/ink-tag.jpg
  banner_img_height: 80
  subtitle: null
about:
  banner_img: https://moran.0oo0.top/images/ink-aboutme.jpg
  banner_img_height: 80
  subtitle: null
  avatar: /images/uploads/yutzi.jpg
  name: 墨染_nlx
  intro: My blog
