 # 主面板背景色
  # Color of main board
  #board_color: rgba(37, 45, 56, 0.6);
  #board_color_dark: rgba(37, 45, 56, 0.6);


navbar:
  blog_title: Ink  Dyeing
  ground_glass:
    enable: true
index:
  banner_img: /images/uploads/none.png
 # banner_img_height: 100
  slogan:
    text: " 墨染水云间，流年如画轻盈了幽闲"
post:
  banner_img: /images/uploads/none.png
  #https://imgapi.xl0408.top/index.php
  banner_img_height: 70
  default_index_img: https://i.imgtg.com/2022/09/14/yAzLX.png
archive:
  banner_img: https://i.imgtg.com/2023/07/07/OxPolU.jpg
  banner_img_height: 80
  subtitle: null
category:
  banner_img: https://i.imgtg.com/2023/07/07/OxPolU.jpghttps://i.imgtg.com/2023/07/07/OxP5BY.jpg
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: https://i.imgtg.com/2023/07/07/OxPBZv.jpg
  banner_img_height: 80
  subtitle: null
about:
  banner_img: https://i.imgtg.com/2023/07/07/OxPTcq.jpg
  banner_img_height: 80
  subtitle: null
  avatar: /images/uploads/yutzi.jpg
  name: 墨染_nlx
  intro: My blog
